# Generated by Django 5.2.7 on 2025-10-19 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actividades", "0001_initial"),
        ("profesores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cupo", models.IntegerField()),
                ("horario", models.TimeField()),
                ("duracion", models.DurationField()),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comisiones",
                        to="actividades.actividad",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comisiones",
                        to="profesores.profesor",
                    ),
                ),
            ],
        ),
    ]
